Feat: Added a default time frame
d-rec/drec-ui pull request #176
Opened 2024-10-07 09:05 UTC by Kingcedru

**Objective:**
- To Add a default time frame for filtering meter reads  on the all reads section.

**Description:**
- Add a default time frame for filtering meter reads on the all reads section.

**Acceptance Criteria:**
- Added a default time frame.
- The time frame can be customized.
- Run tests and check if everything works well.
  - The UI project runs without any issue (doesn't cause any regression error)

2024-10-08 08:37 UTC, divinecharlotte submitted a review, later dismissed
Looks good for now

2024-10-08 13:51 UTC, musayann requested changes

2024-10-08 13:51 UTC, musayann commented on src/app/view/meter-read/all-metereads/all-metereads.component.ts
> +  startDate: Date = new Date(new Date().setMonth(new Date().getMonth() - 1));
let's not add a new class property for this. We only need this value when initializing

2024-10-08 13:51 UTC, musayann commented on src/app/view/meter-read/all-metereads/all-metereads.component.ts
> +    this.FilterForm.controls['start'].setValue(this.startDate);
I would suggest instead to set it to 
```ts
this.FilterForm.controls['start'].setValue(result.commissioningDate || startDate);
```

2024-10-08 13:51 UTC, musayann commented on src/app/view/meter-read/all-metereads/all-metereads.component.ts
> +    this.FilterForm.controls['start'].setValue(this.startDate);
We should set this date to the startDate that you have calculated as a fallback. The default behavior should be to use the `commissioningDate`

2024-10-10 14:36 UTC, musayann approved these changes

2024-10-10 14:36 UTC, merged